---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: _
      spec:
        values:
          defaultPodOptions:
            annotations:
              k8s.ksgate.org/dragonfly-ready: |
                {
                  "apiVersion": "apps/v1",
                  "kind": "StatefulSet",
                  "name": "dragonfly",
                  "namespace": "database",
                  "expression": "resource.status.readyReplicas >= 1"
                }
              k8s.ksgate.org/dragonfly-service: |
                {
                  "apiVersion": "v1",
                  "kind": "Service",
                  "name": "dragonfly",
                  "namespace": "database"
                }
            schedulingGates:
              - name: k8s.ksgate.org/dragonfly-ready
              - name: k8s.ksgate.org/dragonfly-service
