---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    receiver: blackhole
    repeatInterval: 12h
    groupBy:
      - alertname
      - cluster
      - job
    groupWait: 1m
    groupInterval: 5m
    routes:
      # Drop InfoInhibitor
      - receiver: blackhole
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =

      # 1. ALL errors → General
      - receiver: discord-general
        matchers:
          - name: severity
            value: error
            matchType: =

      # 2. Flux non-errors → Flux
      - receiver: discord-flux
        matchers:
          - name: provider
            value: flux
            matchType: =
          - name: severity
            value: error
            matchType: "!="

  inhibitRules:
    - equal:
        - alertname
        - namespace
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =

  receivers:
    - name: blackhole
    - name: discord-general
      discordConfigs:
        - username: General Alerts
          apiURL:
            name: alertmanager-secret
            key: discord_general_webhook_url
    - name: discord-flux
      discordConfigs:
        - username: Flux Alerts
          apiURL:
            name: alertmanager-secret
            key: discord_flux_webhook_url
