---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mc-bluemap
spec:
  hostnames: ["mc-map.${SECRET_DOMAIN}"]
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: minecraft-bluemap
          namespace: games
          port: 8100

