apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:GIOS+9Pkiyw9uY3gPvkgWiv1scTaymoUtxh93pjIJV+P/7msMm3KUQ==,iv:uqxJmrOj5If6HYBNXkX+H3y5vDrzJ/R9bWY9uwn1bfw=,tag:EejSjVbCH4SqhafwQsRH6w==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEZRL3krYUZzUDNaemgz
        cHVPbGc2VVJ1SElqTGV2N0hZWUE4ZVhaTzFJCm5hY3I1ODY3NmNWc0k2WWVvbW03
        K0N1eldCNVY2K2MrN3IwSytZN1NiR2cKLS0tIFJQL2hTaldjcUNza25ySVNIVlZk
        VHFyTzFMaWdWdTZDajJQTUplZitYbzQKJcWD7J57RbjyoH4R0V8v0l863CnZxpUe
        wwNFz5hMyFUnkq7BbtcNEP+75z/aD9ARBHSOL5/uqvK32Xjpo7oN8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:WaXK/I0RlVSFF08ub4XZ/qyR9gylpt6/KHjo/tgylrGsadBR6Jew0qCaZJy26LR7xNy7hKJHtVUb+/UJNTLZksJ/chqJsYksaGFs71EsyiwnIBxCn7NjnVYO67DRhdNJ1zfDlr8xtMJPnmNcryWPG6MqMT/F/UQanTw4XjadNGY=,iv:Cl7MCrdfpg2BL9P4X5VGfG9Fl95Wl03TnRKe4yAxxyE=,tag:FbK1oxA7gFtEM/PGk7Kj1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
