apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:zz4DXgqadWXqg1gaFT1ZzBEXbPITFJgOVlg97vgl2Ub0iJ2Q3wPqtA==,iv:zB7umjwtrpeFo/kkGUAUSzn5qlDy+StNyqdXez3Gcrs=,tag:NEWlfYYprkKm95LWzy95rA==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUFFld0RXWEE3MHRLSE0r
        TkRKMGl5RUt3VStsa2todmRZeTBnTDlkeFZFCnc4Y0t2SWFaSGdZMmFHZW1ZMC9s
        WXhuWVQvK2dsUCt3Vyt4Kzd2aitlVzQKLS0tIG90ZDJxK21YRlpUUzJMSXFNWTFL
        L1VXQ2Q4OUlldytKeGFxQ2tTckprYXcKwZEWgfbUA0QpEoJak3osVgU2dL47zBPF
        TVv9XbZQMqlgiZ8l1GP9kgYaczFJ8k6trUQPiRTOwyCH8tNjZIka7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T19:52:55Z"
  mac: ENC[AES256_GCM,data:lQNAQ6pRrHKeNpZ0lcGMpSXKd5+DEWRef/gbAQuLM8fPkcW5ftUt65ARQapDnIKM4Sq5SWeS1UjhRNEVvmne7OQKZgo8v+OKSHSLRWZ93MRPAZ8V0VtOhurddKKXgXir7EZ99LCzWtZKm48yF6Sp4JKGVlmu9JtvIj2B5MFhwSI=,iv:rEt+7E0TFRfZWIAu0+HxU0VSbD7DXx86SS5WSJ/CsFk=,tag:USLzLoSeBVu9OpOkC5Z2dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
