apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Z1zDkLuXHaF+IB4=,iv:7drdn19GpYDhlx8kEpTRVO/cGZr83h/duj59H+3vwXo=,tag:DKLTk4LPJgfwUxyizKgimA==,type:str]
    TZ: ENC[AES256_GCM,data:TxjOp+Anij0FmPYyu9RIa+A=,iv:TSVAUmPR+lCyzsD5Eh+VcF0KP7Sb4I7h/j1W3RGnJ7Y=,tag:xceI1dQgDShoTgGrwZ4rJQ==,type:str]
    NFS_SERVER_IP: ENC[AES256_GCM,data:Dz5FYwkfXRyg4jJs,iv:AJZxQCIjJDKtsVHy02sqhuMjJQxFQSv3DSobgkp2TQ4=,tag:txA11aYE0/Uqmf+PhTSsQg==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:bof6o3l6t3QYa7A5XdWsZm1TmQTvg1phclg5xA==,iv:zhACCbbugIjesEHYf7Q0Qw8Q8jtZRpzTRPvlMsP/mLU=,tag:aX5JpJlZORKhuaPvTF7DqA==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:Dqw+LkOsE9r6TEIVnSuXcQ==,iv:/p3CcCg6uPwEVlRkf+5aE40VjU1Q0E8x6KLGCUT6MtM=,tag:KMm3ttYjfjJeQcXg6H4iqA==,type:str]
    NFS_PATH_PLEXMEDIA: ENC[AES256_GCM,data:L3bxToIhgBTjtYGcCKtFAaMIVqAF26CcVxM=,iv:6rFxYh7mAJdkRteUvgko7YXtmqxhCKqOLSTVmlxASB8=,tag:QBdTrxAevdZtVEqReQnPiw==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:z5yOe773RbguDMltu5xRcbCMczWfhdm00lMUsYbwLclh,iv:iJQtVrWIXmFkrQL+rOo9jeON+Ms9FvkYgP9/YMgVYrc=,tag:0ZE97hAiOT7d/nx26KGVQg==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:CDaRY4y1nK42NoVdo8X/74VWTS4yOgBpFosVWArCxnWg,iv:pH25Qw/9ZzBsv+G0Dij5XfyyDIx0aZNRWjcOS0QIfPs=,tag:L9Iw5yFV0uBnAFJQ1Z4WrQ==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:LiuC4FOjmxYSKsCRiWNhoezcdxcMQses0eKkN6FJuf4=,iv:Pvh3h4w5oeLx7780bpKPUZbvXmrAIVHpOCijwxD0Amw=,tag:TLqLYkJ8nntQbKok2fprcQ==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:svIRqRq+jt8+cwhrooSjUn/FnIhNtA==,iv:tgQH1+Zss4xkKFoAeG3rF5iCEads7RiR+F6p7bQ7utE=,tag:Gic7C+p+Y5OFdVqz386OEQ==,type:str]
    NFS_PATH_CALIBREAUTOMATED_INGEST: ENC[AES256_GCM,data:xTyTjFQM7kIZpETxU7mlWp7ubdJkbhVOpvF4jB1YcYaXxY65YV2cI1pVlJqvg4DZ8MwW,iv:nyvl1Lyrpt+GphpM/NweCOTNOpDbDOmho4COs8vY/+A=,tag:dpeuKIFo+nh/ArToOPEuhA==,type:str]
    NFS_PATH_CALIBREAUTOMATED_LIB: ENC[AES256_GCM,data:lY8DZHihaw/zTETT2l7uGhsXZPTZ4VGAKxUM9js5k+vk7kWOP1A/yyf09gKgHuJVy87Nbw==,iv:IEZsBLukgnHW4LO70Hh8wjlwy+frgDTxXMlMuB9Y8DY=,tag:5pJXH6w/z2FtHeYxAsKUNQ==,type:str]
    NFS_PATH_NEXTCLOUD: ENC[AES256_GCM,data:JrK+QTA32C6jXrfzJJCVEH/Alrn4gA==,iv:HuOuTyZu9rjqj34SZKXej2ShiwPrFIHfSC7bosZbm0s=,tag:JqfoosjHFUhytZ07NfA89g==,type:str]
    NFS_PATH_K8S: ENC[AES256_GCM,data:3+atavmBtD/OdKbS9h3BJROODRh9lMUO,iv:GDhYRb2JAvCmImZv1OZa7bKUIdN0WguDzbRQ+rqtkPA=,tag:CSP3WqpTqgbaOo8MHZ+ukA==,type:str]
sops:
    age:
        - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBManNERVp0eUdJOTgxblQr
            WmhsOUw0ZG5tbVpzNGIwaUNVNVQyZWZBN2o4CndlZHdwd1ZTYTJkbERuNnl3MmdD
            QWZpdklFUnd4QkN4Mk9wbWxzWW50KzAKLS0tIHJoTVlxRXJJUzNHZ3FOaXRvTkRR
            eVkrWUE2SURHeU41clZzamExTzdhUlEKGoLe9VpmmuHbCnvcHS88POlZVOEYPGsy
            WqbOd9u4l3J/4gyX6plSpnfEaQarJPnipGL9+OwZSI+r0teQdg1l6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T12:50:15Z"
    mac: ENC[AES256_GCM,data:5bHePP8FmZUFrYrPKYsfUnNoS2lZhYbDdSFlobG51ChrYUNpWkf/XKQdnPEsCKeBYd2ULmgo1ADVtdoV/UAJiBGe8bvyeHmhlFdRfLN/lmD+N0QyLyUIiX5Xs4CW7112t5V9t05nivc3jWBl0EN3pDkZA0LNE7GXvjN5B20Y75Y=,iv:X+9f68ie5rzFNfox71+3KH+bLsKe6WGeHJKtsiuXSck=,tag:AsLYkzPTou1zlKHvFA4dcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
