apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Z1zDkLuXHaF+IB4=,iv:7drdn19GpYDhlx8kEpTRVO/cGZr83h/duj59H+3vwXo=,tag:DKLTk4LPJgfwUxyizKgimA==,type:str]
sops:
    age:
        - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBManNERVp0eUdJOTgxblQr
            WmhsOUw0ZG5tbVpzNGIwaUNVNVQyZWZBN2o4CndlZHdwd1ZTYTJkbERuNnl3MmdD
            QWZpdklFUnd4QkN4Mk9wbWxzWW50KzAKLS0tIHJoTVlxRXJJUzNHZ3FOaXRvTkRR
            eVkrWUE2SURHeU41clZzamExTzdhUlEKGoLe9VpmmuHbCnvcHS88POlZVOEYPGsy
            WqbOd9u4l3J/4gyX6plSpnfEaQarJPnipGL9+OwZSI+r0teQdg1l6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T14:31:40Z"
    mac: ENC[AES256_GCM,data:IBrF6za2bmFeKBxFlqGviU/eveDwiOnwp5QNS0NSN9p+zZ4/KJ+qLRJBd65/OuIXIQyZhBCG3skbMNJuJS/cMDuyO6q521SiiUhwvwPp7DBpn2xDm9x8w7EQCF4Mu0pibvUoj+ka7c6gHXI1OfGBY0nT6MikjrwwBfDNVV2MKzE=,iv:B09gKkVRmMdQ0IBM/PneGxgltDjjJZgbBIX9YuT1YhE=,tag:XHcS2h1dPPExx5HKejG3nA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
