apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:wryljyVL9szJB14=,iv:IsyvpNHh2sbnpPoQujYOnIDe05jq6I7KT9wXALFVW7I=,tag:oJcAGoPKzPQacM8qXYnhrg==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQVM3bUNlV1E0V3crbEJz
        MTZ0VkFiNDZCOTNDR1Y4N2xKVERjdlNCNzJNCjZ5djk0YWYvNFkyaDdseldvUXVI
        eE5jMHp5RFc5UW1sMHdVcFdGNVFJODAKLS0tIEhqZTB1SkcwZ3cwbHpzSEtZR0Vh
        WVdhTnpGRjZGZXhmY0tXZjhDWjlnMXcKEiaGg6ZKiamdjR2l8+5wtvPxzFRPi47L
        DQAJErgUkjYlxdSgvY3AUyhXrwdej5XyKYsw5XdQpdktYhtt9tX7ZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T19:52:55Z"
  mac: ENC[AES256_GCM,data:1H5yuzORnrpPRiBZF3xPaG+mGFp1OeXQ+nvx39S2P8lZefqPNLTd/inxawPecD95QdKmr0GReqXUzUKjP3Absc/BKs22eQl63TspbBarEpjXWkBW80QewyVhnLrHHSJQYgNdRvI1s/CswT8FIU2OmFSC46lSb52Iii054k9C/ks=,iv:3ka0PK7S2FhnkclwnWC7q6YTu651dfyPwsF2/TUyaZo=,tag:BWY07vqFVMsXGhUoqSPDmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
