apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Z1zDkLuXHaF+IB4=,iv:7drdn19GpYDhlx8kEpTRVO/cGZr83h/duj59H+3vwXo=,tag:DKLTk4LPJgfwUxyizKgimA==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBManNERVp0eUdJOTgxblQr
        WmhsOUw0ZG5tbVpzNGIwaUNVNVQyZWZBN2o4CndlZHdwd1ZTYTJkbERuNnl3MmdD
        QWZpdklFUnd4QkN4Mk9wbWxzWW50KzAKLS0tIHJoTVlxRXJJUzNHZ3FOaXRvTkRR
        eVkrWUE2SURHeU41clZzamExTzdhUlEKGoLe9VpmmuHbCnvcHS88POlZVOEYPGsy
        WqbOd9u4l3J/4gyX6plSpnfEaQarJPnipGL9+OwZSI+r0teQdg1l6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:hlWycMSJ2+M0w6tqHCmgcLNn5TNxACJnTuK9XF63Z51BVK2Hj/CMFbl3o2nNFbIbd3+G/dBqnxz2bKk+Umn4B3oumt7ZsCP+Cp4UJ2Ga9EPKLheZEHkREvOyd2pj6hGwbdLhXafP6vwZDrx7Q8A+c/7254RnK/MpE6a3ZET24SY=,iv:SogWY1ixOhq0XWhbYUE57gTgvCJhapQGcyN46uI8zio=,tag:UY6zffMlr60qCAQAM/ANhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
