---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app infisical
spec:
  interval: 30m
  chart:
    spec:
      chart: infisical-standalone
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: infisical
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    nameOverride: *app

    infisical:
      replicaCount: 1
      image:
        repository: infisical/infisical
        tag: "v0.154.0"
        pullPolicy: IfNotPresent

      env:
        - name: REDIS_URL
          value: "redis://dragonfly.database.svc.cluster.local:6379/1"

    postgresql:
      enabled: false
      useExistingPostgresSecret:
        enabled: true
        existingConnectionStringSecret:
          name: postgres-app
          key: uri

    redis:
      enabled: false
      usePassword: false
      fullnameOverride: dragonfly.database.svc.cluster.local

    ingress:
      enabled: false
      nginx:
        enabled: false
