apiVersion: v1
kind: Secret
metadata:
    name: infisical-secrets
    namespace: infisical
type: Opaque
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:PUx57VOgOxcsVebyLTUrFTKRHL+7BHlkQInRm9opSQbjnxRbIIFIM4xrgAs=,iv:D0vqz8Wpy04oJpgvlbcr6GfxW4Rn9eDqJHis8T85dpE=,tag:eGkcSSPXKHE8VlMLL7tkXg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:WuIXRMxME2EuWDVnC6tmKg1++bOc0Nf3LHU6b+1/+AU=,iv:Le8oUYV6JPbms3M4J3wdBni+DzRl0LQ6gnxQre1O+fE=,tag:YDU34BBdEuBpgHHLc/BmIA==,type:str]
    SITE_URL: ENC[AES256_GCM,data:IvXXJTRmGFNAv3T4iBsif4HDZ5WiO/upcsSOKrg1N373xQ==,iv:ETgJcwPW88uRAsfaQez6He8RCW1Ns8Y3lbFTImujk9c=,tag:08X3fHJgkj6vBx0Zk6Nm+g==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Ad/yQvgqtL3FI0hUXMccNfOZOPh5oCriSxS0+OEHO4Oevy7SiQsCb91O8k9knrL/4nLt,iv:ccd3ogozBJW+pGfIZYCbtFPO7+XyN645G/VepxAKrok=,tag:rB0bvKfbFTqhCdFFoTUx5w==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:EtpyECPbR+jzD/JTu/suOZ2amVvTEZgvBHi1Spb2Kubp,iv:Uij5jcri4uGJWqyzRgqrnIc4IxVeCaEuhyAc5puw6xk=,tag:R7O4ekZYwI51HGh0t9JGeg==,type:str]
    SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:2wTjcEeeUeTUlxsyAU4TfwDSnzdqQXk=,iv:WfAUsJKOqjuJ5hqlH4ixv5DR8/bzO+QeLKopOk9WEpM=,tag:OHpynG2RN5/yzdOFlH+Z7g==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:KGbcnMsr6Dsd,iv:5RwS1JgFIy5V2fh+OY6rm+G1wcH3L7BuFTx/z6GX6aU=,tag:lyzV4UucasUFwVWTIQWgWQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:rbF6pw==,iv:3Fug9zIXN/RlVnnVgQYBo07OFuvDo6r2iU5umpV0TH4=,tag:L7787KmIvwELJR3mqLACGg==,type:str]
    SMTP_IGNORE_TLS: ENC[AES256_GCM,data:rOioRw==,iv:riWmPffiUxKurBmWdaRw79VGvpIJ/VVDvxvj3XfNM/Q=,tag:7GGn4DC0ir+4GtPWGEb1mw==,type:str]
    SMTP_REQUIRE_TLS: ENC[AES256_GCM,data:uqRyMAI=,iv:CCjOl81aKqOFAOZjqeQscsI2g0bfIER9kQQ4o77ZraU=,tag:gkzvq3Cw0ZoeHes7xr+7bA==,type:str]
sops:
    age:
        - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU2tuY0NjYzV6dHd0N0My
            NXRrM2J4L0hxVnk1TWFXRmRtRFJoNHdMTmxVCmJlS1dxR0lDM1gwQWRpNGZONWl6
            TFFKZjZBaG9yclVRaFlKZ2hiU2NiOTAKLS0tIDhSWUIwcG9iRFJPdzBTZExUYXRD
            MERSUWFpY2t6UUVPM2Q1MUFqMHJHbWcKW4yTYFfIJuMqz9sf4zgQhnu1sqqV8fOx
            Sv0134wKAlJe9rbj1bGHShc2V3jnfsH2FC86S1B05R3vQ6oGOQ3ANA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T11:51:10Z"
    mac: ENC[AES256_GCM,data:TrGIY8+Dy4ahnPHyocxawh1DyckuAZKgb2Mu/MRxGIvSQtPcts+Z2SQDx+Nq1O/xs++C2ClGbOC/LILOm0t6MeXJo0Wl+jpDuhfuHwWQhI38PQQ/QKjG1NZsjpkQq5JLpasqzE9VLviI5GmFSSjwwNbtESpbsfYi7GwigqdaMDo=,iv:mZKDzzjX+g+7VfGkn8Ku3rxJbsauo6oX8+sRE6n6fK8=,tag:bTYmRUidZg75CpiLBz6vow==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
