apiVersion: v1
kind: Secret
metadata:
    name: infisical-secrets
    namespace: infisical
type: Opaque
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:PUx57VOgOxcsVebyLTUrFTKRHL+7BHlkQInRm9opSQbjnxRbIIFIM4xrgAs=,iv:D0vqz8Wpy04oJpgvlbcr6GfxW4Rn9eDqJHis8T85dpE=,tag:eGkcSSPXKHE8VlMLL7tkXg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:WuIXRMxME2EuWDVnC6tmKg1++bOc0Nf3LHU6b+1/+AU=,iv:Le8oUYV6JPbms3M4J3wdBni+DzRl0LQ6gnxQre1O+fE=,tag:YDU34BBdEuBpgHHLc/BmIA==,type:str]
    SITE_URL: ENC[AES256_GCM,data:IvXXJTRmGFNAv3T4iBsif4HDZ5WiO/upcsSOKrg1N373xQ==,iv:ETgJcwPW88uRAsfaQez6He8RCW1Ns8Y3lbFTImujk9c=,tag:08X3fHJgkj6vBx0Zk6Nm+g==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Ad/yQvgqtL3FI0hUXMccNfOZOPh5oCriSxS0+OEHO4Oevy7SiQsCb91O8k9knrL/4nLt,iv:ccd3ogozBJW+pGfIZYCbtFPO7+XyN645G/VepxAKrok=,tag:rB0bvKfbFTqhCdFFoTUx5w==,type:str]
sops:
    age:
        - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU2tuY0NjYzV6dHd0N0My
            NXRrM2J4L0hxVnk1TWFXRmRtRFJoNHdMTmxVCmJlS1dxR0lDM1gwQWRpNGZONWl6
            TFFKZjZBaG9yclVRaFlKZ2hiU2NiOTAKLS0tIDhSWUIwcG9iRFJPdzBTZExUYXRD
            MERSUWFpY2t6UUVPM2Q1MUFqMHJHbWcKW4yTYFfIJuMqz9sf4zgQhnu1sqqV8fOx
            Sv0134wKAlJe9rbj1bGHShc2V3jnfsH2FC86S1B05R3vQ6oGOQ3ANA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T16:09:51Z"
    mac: ENC[AES256_GCM,data:Yytm+AfdpDTuZUNESnYE6R+ffot8iQWtCTdiKqSKh9AvBWrKsx0C3Ssf2dm2wyYFS7RCCV5UStiCqPep8q1XPIa1tl05jcKrc79G/a65W08vXGSHzqtW0x3eL9WyNXWw/T76p/8JB/x9wN5xgUm1PqhFym7y13wXEA1dGZ3aGXo=,iv:za729g1WvWigqUuLB3iVQ1IpsZ6Bww5zXwLIXn8c5/g=,tag:lbiTD8d8UxQUihjxM2fLMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
