---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux
spec:
  providerRef:
    name: flux
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: "*"
  exclusionList:
    - error.*lookup.*github
    - dial.*tcp.*timeout
    - waiting.*socket
  suspend: false
