apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:a4+RfqzxAI91nTJGZ9pHtW0UfG0dcrL40wCx0aggRyg=,iv:sGC4KqJkEbXn6sY2jWdPBK8v1HNrNImR5UZ+GdxjdnY=,tag:UsKqg2DJJhmwP2dS0YlbEQ==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsamROME5YaUtieXVCMk94
        K0V4OGRaY3pMWVl2Tm1DeXV4REQvV2loVnljCms5YzJQMUE1cVVYOXk1ZmpvRXBo
        dXVHdjNiQlczNGJpRVpLcDd0cGYyQjgKLS0tIHlUT1VwMTlTTEp1NXRUU2VWOFpG
        ZnBISkVLNlBzMkpMOEFYUUltazRkZ2sK8UC53P4BELi8hz+6u7pXDAuT8VySVofO
        jlwmc5EGNpsP+4se3Qy9QepNzsKpd9uv3S7qiUNP5UXLZRaAoMia7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T19:52:55Z"
  mac: ENC[AES256_GCM,data:TSt0kBnqHgudpOrw1qzf9S9jLt2h5DjxzvfrX3SzsuM1FsZJuBWLXNBv4kQsKMBim2CCqRhUrtk32ZKa4/UTQApactSYmZ/3xQxQs+N2xiyqul3VAm8SIr4VJtV6+tQ73ext31Zttk0fmdSZP6mPLknCFh9QgszVBTfV+b+CuMk=,iv:NFtU9EWlWWjPdLdfrHbnp/u2XYADj42YsG98LAZyKhg=,tag:YvVJq54p0jGWGBjwIig4kw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
