apiVersion: v1
kind: Secret
metadata:
    name: discord-flux-secret
stringData:
    address: ENC[AES256_GCM,data:4Vm+S7Lke6OVbHyPBNit7wHAuxXet0oLvFwLHXJPyztZgqqm6rIkBU9qw6AlOFkahtYr+SIK923X19SF88hdWDUFmus6xrxQDvibnzxyxhga280PgoFIgzAUKYPWgEPtIzLvS9Bzk5ipd7f+d5b5/h/7l89Ky0I/8g==,iv:OC37j56JBaNkJvNISuDYK+BaC4QhSwPB5FoOUjzt/8Y=,tag:sEliQKdcj8EWpcggRoIryw==,type:str]
sops:
    age:
        - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0lWelJTK3h3cUUyVnVR
            NjFKTUY4RmdkajFGOHdzdVFGNkNkR1llaWpJCnAzMEpoN2ZtR3J3TmR0ZlZTazR0
            d2FkZGpvajN0OGhjMS9tZkU4aTUrcDAKLS0tIG9nbm1OT2MxMXpmOGZuckpPU1ZK
            aFJ2c0hxTkxBQmM3enZrUEFlQng3aDAKuAk2yfJi4045YXA3CrLXOuBT/qMLuu5D
            lqfp6QattCNcs484+yB2GzWKZbNst1myVIfZUoZI0oBxlHiSyfM4Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T13:47:12Z"
    mac: ENC[AES256_GCM,data:M4k3Bouo9SCL1M0skVtMuIAJU5ZOuca+uN+I00pwczyzVx77zmfd/WmhHFF8nT4WhbX/VAmfZTgtaDh8FbfO+GtE8SMWrN4FkSFVVHEkG1W/SVwdqz4sKmHTEfeQ23uZZIGeAL2u8OfSjO9hi0DerWncobbi7qK2bH+3HePk6i4=,iv:uKEZrqM8Qt8NiKwzJ7As8pBamBibA6YrMN05nCaz9ig=,tag:3+K0A/BA0SGhQxSRyKHCDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
