apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:V1rLbkmLBJvuZQkgxZC6Ml2Bi44rGoqr+ULWcQzQGOU=,iv:tCa1MHTnJC9LxTvIHZhn3oK+u0Q9PWCwJfXRB+kN8cE=,tag:IQiPt5P6IcZPIBF/rG7X3A==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0lWelJTK3h3cUUyVnVR
        NjFKTUY4RmdkajFGOHdzdVFGNkNkR1llaWpJCnAzMEpoN2ZtR3J3TmR0ZlZTazR0
        d2FkZGpvajN0OGhjMS9tZkU4aTUrcDAKLS0tIG9nbm1OT2MxMXpmOGZuckpPU1ZK
        aFJ2c0hxTkxBQmM3enZrUEFlQng3aDAKuAk2yfJi4045YXA3CrLXOuBT/qMLuu5D
        lqfp6QattCNcs484+yB2GzWKZbNst1myVIfZUoZI0oBxlHiSyfM4Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:gdgQ1clWBC0kiTRxay0OIeqRb9L13QVL8ic7PHYiFR+8p0q66QshUoalubQCCA/LWOVNOrKNHITsHjPvy7/Z0a51RWbFr2UoCebZ+X9OwaGnX9uMKtHhLpEQshNlhHJSeb81ZopgIeNSwPvuPNfy4uFCYAt9KP90zlDF437Yu2U=,iv:0p0t4UX1mRX/0UTyaZ9tm/m1fww2PyUhq6+DJYs1vSU=,tag:sAk8I4527jXabZKhkVG7+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
