apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:Jr6eGScWxkzaK7UGUQdPJoYci5mIiAM=,iv:TxYwSYb0RiluuDz8meBeGWB56hlRWdOPblwal16H+L4=,tag:2FjBPo5gW+s7gUQTVQ7MnQ==,type:str]
sops:
    age:
        - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU2tuY0NjYzV6dHd0N0My
            NXRrM2J4L0hxVnk1TWFXRmRtRFJoNHdMTmxVCmJlS1dxR0lDM1gwQWRpNGZONWl6
            TFFKZjZBaG9yclVRaFlKZ2hiU2NiOTAKLS0tIDhSWUIwcG9iRFJPdzBTZExUYXRD
            MERSUWFpY2t6UUVPM2Q1MUFqMHJHbWcKW4yTYFfIJuMqz9sf4zgQhnu1sqqV8fOx
            Sv0134wKAlJe9rbj1bGHShc2V3jnfsH2FC86S1B05R3vQ6oGOQ3ANA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T13:28:19Z"
    mac: ENC[AES256_GCM,data:GrLPP6IH4gVq8dTO63IIF5nVmpL7UYG/kF6Pi6DI7QoCx/X7JPwgO/Py6e8f/0UlOtEdylvSiVJ+bp7stJqugPf+n6bswqMLMTttDOEFlHiWXNpeBqvUyZIgJYMLlD7qPOpEyrXeCF019Vf9NVQnBR146Ys/DFrGUSXlTeX+FJI=,iv:uMN2u24KNW319oUm2PzCfGc/ZixQK194nt/UaTEAnBE=,tag:jT7A5ffcFwSJKWbRqB195w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
