apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:cIYAnI1JZWm76vj/EOju9Koo3xJSm7LaWw==,iv:EiZRyCg9kibJLYTJUOOOVr0yTu7trEPtPM86D2fbqoA=,tag:FAAAlFW35q/dSINklXNRhQ==,type:str]
sops:
    age:
        - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU2tuY0NjYzV6dHd0N0My
            NXRrM2J4L0hxVnk1TWFXRmRtRFJoNHdMTmxVCmJlS1dxR0lDM1gwQWRpNGZONWl6
            TFFKZjZBaG9yclVRaFlKZ2hiU2NiOTAKLS0tIDhSWUIwcG9iRFJPdzBTZExUYXRD
            MERSUWFpY2t6UUVPM2Q1MUFqMHJHbWcKW4yTYFfIJuMqz9sf4zgQhnu1sqqV8fOx
            Sv0134wKAlJe9rbj1bGHShc2V3jnfsH2FC86S1B05R3vQ6oGOQ3ANA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T10:54:03Z"
    mac: ENC[AES256_GCM,data:6B+zwaKGhEQIz0dBLuTUe2wo6AGleGrfETwLMsV5FaBzvHnLgJ3rwaAZ+BPCsRMfv9bn2vdObgtkMyeN9hbKvzK69ZSNPve4fDsiOR1qs47Qx/XgG0/KEJlr8GebJ0ukMEs1bJqU0Mx78Qg/Wd4Rw4RqWniDisnb8vN2VmtX0MU=,iv:i+ruybsqGMh1ccivCSEL6Jh7iZZGcMdUFf/B/3uXlsM=,tag:zki8no2rE3XzWoUqSyVtBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
