---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./wyoming-whisper/ks.yaml
  - ./wyoming-piper/ks.yaml
