---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./echo/ks.yaml
  - ./radarr/ks.yaml
  - ./static/ks.yaml
  - ./mailpit/ks.yaml
  - ./seerr/ks.yaml
  - ./ntfy/ks.yaml
