apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:PzfsoUpnS1NNuZPrWqfytxu+g2rOdyZp+osOHoBgbiUUjuCm8W7H9nAuvOj9ScmOf9mGsDTWTs0r1pNCh7bsBX9voepDijMpY7oPZLIDHP3xq8bouARtb9GFS1l8qGBopq5NjHS/A1bRDe8/0XvKaENDxVgY1/DVizbb8zObD+wXs8iPFrhJ3N+uqh7ri1RCXnUhf+0PqwnJVlMdl532Jzh7jE3suGt331pLigEHV4rnG26I,iv:gimDtzMfyzXphFvVmm0ZdnZoH9X9nSae8oIJjxeHPr8=,tag:1gW1ieKN96oXF0RPRKf4ow==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTktmV1RIV0czd0hZMEph
        b2Q2alU2TlJHS2lad3ZQTmkzZDdxcWdUSmdBCnUrUUgxY3ZFd0VMS2dFTElaQWNr
        UHZTMThHbDNqaEZEaExLSi9ISFMrQlkKLS0tIFJtYldSMTRXTm1janJxSEN3OTJD
        M0xyNTRuTldkbVN2dS9mM2xkVExKNEUKtlamvKoyhiyVyfdxDGbyF6v1VUK2Iwpl
        D/SdtH0ofOLJxT1xvh59KqTjDY6uFIYKpHjnGslyLicCA6/A+LQaow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:uK4hehwbm5A0ceuSRn82jOI1hP/QXQooIWsaia4xxruviHvL82GQwFsRPJsapvvlyiIZQH6mlz2xWYaQK3hgKrq2EqoyMlK3lSX5QaBL5sHqoNK1jehg8sJ9u6Li8sXS7rF05PA9t5JtyEfglKL+C2Sdygh65P0pVpzs4SkSrbI=,iv:rKhTfFUyPEIjSVoHj3IoSDf2GMcKlTsL7j8/knDVGn4=,tag:z3tQ4cnzf2BL+8gBTbsPUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
