apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:JI1CwtzbZ5oWP0SxAd02H9V+/W8ogqX16mMo6AJujb9jK+cllAX2XCgtXNawyzac7gVw6m5+84WgrfufDx5GuzZi0qhokRvpIz9dawC/1/Vm59UyFW31Nu51nrLf1pWq2i1vyFpadCYZkZhRQvHlZ8/WRbwyWIo+r/z/0dwthEGdKfVVyJPo6spVLtKU/dOsj6FXr0sTc9wnCxXn08kzfi8odbXSdLlafrM+Q7tHiK2qr74R,iv:mxd7NQzu5mELaA5FoGnPyghIYOzP4A/fJFP2zDrOnHQ=,tag:19DIpLdi60IUWuImR2lTgg==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbG1SUXVuQ3diZHJVUkpz
        L2hHZVY5RXVycitiU2JMS2tTa3ZIY1JWcENBCnZ3VlBDSEdiL3hFaGxtZzFjclE0
        WjlDa2dPbmtvTXJTcXBMZlFsazhUZU0KLS0tIGVBcEF2YVNOTGh1bmpKN0k4UE56
        TEpHcVhUQmJFN3FoWmxGTC82RW1IMncK7S7Jh4+Rl8TjTjrcbzwfw0uWIVPMHoDf
        nE1vGXC38gOayK2zIHOeVk3j9bfR8JmLC7D0YCXk2hpPv+/Vt18dOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T19:52:55Z"
  mac: ENC[AES256_GCM,data:36kQEiZ1xd41ygaL9X2XWLzQ6L5gZk/4y3QoM4xRE6jy8wxnBDQ0IDPKmZCOvXLERWWtfEgitsAZKZaOkn7035QrkWcA21gKcKMRDrvSa0WooIGjCJx8avesRuMmUf0moROe6Zt/HmTc/N3WkeGBH0AYw7ErOkiSMiMYmO8GeC0=,iv:fDaaIWlTrlKstFzeuMmNesQvJ+Hb2oKAv9d/OMyGowU=,tag:/NrbkfZ2I36wGKpbb2C5vg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
