---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./base/ks.yaml
  - ./base/pass
patches:
  - target:
      kind: Cluster
      name: postgres
    patch: |-
      - op: add
        path: /spec/managed/roles/-
        value:
          name: ${APP}
          login: true
          ensure: present
          superuser: false
          disablePassword: false
          passwordSecret:
            name: ${APP}-postgres
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: _
      spec:
        values:
          defaultPodOptions:
            annotations:
              k8s.ksgate.org/postgres-ready: |
                {
                  "apiVersion": "postgresql.cnpg.io/v1",
                  "kind": "Cluster",
                  "name": "postgres",
                  "namespace": "database",
                  "expression": "resource.status.readyInstances >= 1"
                }
              k8s.ksgate.org/postgres-service: |
                {
                  "apiVersion": "v1",
                  "kind": "Service",
                  "name": "postgres-rw",
                  "namespace": "database"
                }
              k8s.ksgate.org/database-applied: |
                {
                  "apiVersion": "postgresql.cnpg.io/v1",
                  "kind": "Database",
                  "name": "postgres-${APP}",
                  "namespace": "database",
                  "expression": "resource.status.applied"
                }
            schedulingGates:
              - name: k8s.ksgate.org/postgres-ready
              - name: k8s.ksgate.org/postgres-service
              - name: k8s.ksgate.org/database-applied
