---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs-tcp
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter-nfs.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - truenas:2049
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-nfs
      action: replace
