---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seerr-private-deny
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - seerr.${SECRET_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/status
        - path:
            type: PathPrefix
            value: /api/v1/settings/public
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.envoyproxy.io
            kind: HTTPRouteFilter
            name: static-401
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seerr-private-allow
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - seerr.${SECRET_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/status
          headers:
            - name: Cookie
              type: RegularExpression
              value: ".*connect.sid=.*"
        - path:
            type: PathPrefix
            value: /api/v1/settings/public
          headers:
            - name: Cookie
              type: RegularExpression
              value: ".*connect.sid=.*"
      backendRefs:
        - name: seerr
          port: 80
