apiVersion: v1
kind: Secret
metadata:
    name: docker-registry-ghcr
    type: kubernetes.io/dockerconfigjson
stringData:
    dockerconfigjson: ENC[AES256_GCM,data:XLIIaUZDFWewD83x7AbY++0M+wMcyrgpmhzpiUrLy0CTFoBANvLpYwD2zD957VdCRbJz/akVmjrqtYpkfYXh7SrMV/40IXn0zvlEm6avsMc2f0WWlqy8iLeuKW69fdga/+vF/FRWBMlXcmU3xWFuwrQ7q/v9EkiLKde2r5x8e7Supet0jTaEYKwZdqYjDrcL/PRbra8VjiVZ8UT4sahXRb7pZqduMlgxR/cACr7nK4VtLA==,iv:DaWUZovBSVsd0G0QRXM9ITgT1G+dG/3lNlxPED1LFns=,tag:OFejvxL69hpMdP11osHEfw==,type:str]
sops:
    age:
        - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBManNERVp0eUdJOTgxblQr
            WmhsOUw0ZG5tbVpzNGIwaUNVNVQyZWZBN2o4CndlZHdwd1ZTYTJkbERuNnl3MmdD
            QWZpdklFUnd4QkN4Mk9wbWxzWW50KzAKLS0tIHJoTVlxRXJJUzNHZ3FOaXRvTkRR
            eVkrWUE2SURHeU41clZzamExTzdhUlEKGoLe9VpmmuHbCnvcHS88POlZVOEYPGsy
            WqbOd9u4l3J/4gyX6plSpnfEaQarJPnipGL9+OwZSI+r0teQdg1l6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T19:07:37Z"
    mac: ENC[AES256_GCM,data:GVVEmJUhaDcigD7nVxWg9PIt9Xv9GLsmPsdYViv3liDsrwRfz9aKEuAOgKG371UDcq4XfABJ0Vq03TjZQzqsb2X31oKv/dAlwXq5zqWJHuonphFaNONwUhybAz2s/KJu9D7KyBr7XF0tqZNPB66jxTcazeSiBrCY6wS9WSwsL0k=,iv:/AO2I2wBGG2wDpBf28VvIpZyuvQKZhoBE6ec+rXbJgw=,tag:nqSfMJ3wLRFhvdBBH/F7FQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
