apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:cGRNDWJByTlrv3gPw8U/ubiyCJ3KlHsivjQNtkYYAil00s9aIbe+7g==,iv:ecE136YXA0lyALjHQhr0n/PCBZgrfLiqnpMhQq6+vUU=,tag:H+YJacVVgWe51QzNzNAZqQ==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcFRkLzdjNnlHVkFuTVdr
        a3pBamVpRWhhdWNxcGdxcDdNSWJiNGEzNUhjCm9pQ0t6YUR2dE5hZ2NYQytaYmlm
        ODRuSWpLVm16QUNFTjVHU3Z2dFgxMVkKLS0tIDVxZktoTlNFOUp2aVU1S3BsbHFD
        UTdlWUw1UFplb3dZWUU5WTZTb0t3ejAKenKHrfWSPVRQVTlA4XBhkVIpj0vX/afO
        34Z/LnzGcCJcrE64OMLGfO2yi9yFcuMd5bh9qCoWtC6EHJhYWAhf2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T16:10:50Z"
  mac: ENC[AES256_GCM,data:L4IRCAbSs9S4GDxXtMQ+c/73q+mvFuFCZItVW6L4W8KIP9eezjF8YQ/iJ3vR1EhWQEVlmr/G19J4CbSZfXlpQNUaz5GB3iRT13Gt1DeDw6allalRG8ldYMCTX52GEftSM+/zohV+XZMon3rMH2GBXhNzNdABEZO55soeiU3k+NM=,iv:+4T4BiA5idUOI0KsmYJZ3uWKAuvTzQdwbiQfx7eldtQ=,tag:JC1gTrtk3tNVb/mXqDxH8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
