apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7wa3J2NcyoxxscMKzof2REMSVafGDxwfpNjT2ypWHbqU6cgrwmkyBA==,iv:o1MnaJqoNOtqh7QmcaOj40mgeOOckVaHDLFrI4/TQ8g=,tag:fKOJslxSgV00LAeCttxFew==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdzVGb2g3aXhGNExmbmtZ
        aU8rb0F4TU9JL2kzTTg0cTRzdUpwaGZjLzFjClR2bnJnWnl6WDRKY25Cc1ZKdkQ2
        S3hLZnJ6SVBmOEVSVUs3VDFsenQ2TmsKLS0tIGVFckI4ME90VlhXWVAxV2MzNS9L
        RlFZTElsN00ybkxtVmlmV1h6TGowblEKVA7RgCExWqTwxTUusAmEfO8MV6SfKUP5
        1KZOkRGs2gybAlhNbB72HjT8km9EBinsNMeGtOH3RCyrTAyYJuzwwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T19:52:55Z"
  mac: ENC[AES256_GCM,data:GWm96olT96/CwylEg8UkaS+WF4KISdEavbxR5sdML/k+g5aLL9eI+686JWbGDD7ssMqLroCy3y9puJJ9CIZfvW06EoArVKuSjRe7vVYlnKeS7OiioQbCxtmFDDRuAmqE2Ch4l+e6bDlp9qtt96sG9bR/wCdVkAnL+SoPxQW5Icg=,iv:hz4wDn8gkBDmVXzaZzfeZn7dxjMlnvQ1ReztJAtZjVg=,tag:93gXyQVbhuKs9hBGn9+EKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
