---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.10.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.10.20"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-01"
    ipAddress: "192.168.10.10"
    installDiskSelector:
      serial: "50026B7383F0C77C"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/dc861599b458d7902682bf4d545139d2b0628eb705efbb113ed6608b6e6807fa
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "38:05:25:33:bb:74"
        dhcp: false
        addresses:
          - "192.168.10.10/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.10.1"
        mtu: 1500
        vip:
          ip: "192.168.10.20"
  # - hostname: "talos-02"
  #   ipAddress: "192.168.10.11"
  #   installDisk: "/dev/sda"
  #   machineSpec:
  #     secureboot: false
  #   talosImageURL: factory.talos.dev/installer/b51b7b6129e8ba285ab83ef1059418c434de4223a7ae4b3905dd06512b923943
  #   controlPlane: true
  #   networkInterfaces:
  #     - deviceSelector:
  #         hardwareAddr: "08:00:27:0c:85:f5"
  #       dhcp: false
  #       addresses:
  #         - "192.168.10.11/24"
  #       routes:
  #         - network: "0.0.0.0/0"
  #           gateway: "192.168.10.1"
  #       mtu: 1500
  #       vip:
  #         ip: "192.168.10.20"
  # - hostname: "talos-03"
  #   ipAddress: "192.168.10.12"
  #   installDisk: "/dev/sda"
  #   machineSpec:
  #     secureboot: false
  #   talosImageURL: factory.talos.dev/installer/b51b7b6129e8ba285ab83ef1059418c434de4223a7ae4b3905dd06512b923943
  #   controlPlane: true
  #   networkInterfaces:
  #     - deviceSelector:
  #         hardwareAddr: "08:00:27:1d:06:2e"
  #       dhcp: false
  #       addresses:
  #         - "192.168.10.12/24"
  #       routes:
  #         - network: "0.0.0.0/0"
  #           gateway: "192.168.10.1"
  #       mtu: 1500
  #       vip:
  #         ip: "192.168.10.20"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-storage.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-nut.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-features.yaml"

