---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
  namespace: media
spec:
  storageClassName: media-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_PATH_MEDIA}
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: media
spec:
  storageClassName: media-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-nfs-pv
  namespace: media
spec:
  storageClassName: plex-media-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_PATH_PLEXMEDIA}
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-nfs-pvc
  namespace: media
spec:
  storageClassName: plex-media-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-series-nfs-pv
  namespace: media
spec:
  storageClassName: media-series-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_PATH_MEDIA_SERIES}
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-series-nfs-pvc
  namespace: media
spec:
  storageClassName: media-series-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-nfs-pv
  namespace: media
spec:
  storageClassName: media-movies-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_PATH_MEDIA_MOVIES}
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-nfs-pvc
  namespace: media
spec:
  storageClassName: media-movies-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-books-nfs-pv
  namespace: media
spec:
  storageClassName: media-books-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_PATH_MEDIA_BOOKS}
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-books-nfs-pvc
  namespace: media
spec:
  storageClassName: media-books-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-anime-nfs-pv
  namespace: media
spec:
  storageClassName: media-anime-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_PATH_MEDIA_ANIME}
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-anime-nfs-pvc
  namespace: media
spec:
  storageClassName: media-anime-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
