---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./victoria-logs/ks.yaml
  - ./fluent-bit/ks.yaml
  - ./gatus/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./keda/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./silence-operator/ks.yaml
  - ./vpa/ks.yaml
  - ./goldilocks/ks.yaml
