---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router-voice
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mc-router-voice
  dependsOn: []
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      router:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: jschuler99/svc-router
              pullPolicy: IfNotPresent
              tag: 0.0.1
    service:
      router-api:
        ports:
          api:
            port: 8080
      router-voice:
        annotations:
          lbipam.cilium.io/ips: 192.168.10.30
        type: LoadBalancer
        ports:
          voice:
            port: 24454
            protocol: UDP
