apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
type: Opaque
stringData:
  clientId: ENC[AES256_GCM,data:BKH9IUpKn5R+7vwqeefTyxmSp/GUF1H0G3FYVB+fgodCr9xN,iv:i0u+BTzPj2fbWNhlx2eVQf4AkK3i2AAVXWF/EKJbD/I=,tag:AfslX+l1LXqy9wbrUU5bmA==,type:str]
  clientSecret: ENC[AES256_GCM,data:KLOvRgep/g781lWup13cGqMw9TNCnCk1lTjKp0O5hvMGTnsXnD1NjdgvvYyuyp5Tzjpq1zY9ruVhfDJHLXs8dw==,iv:oyL8hKSilWxZ03Q3g3qZ/0V5sVue2xaxY/EgKXcLH+4=,tag:hHCgbEDLxLXBsnS5xfta5g==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRmxON0tERVhzRVE5M3kr
        dWMyT2VDTnZFMzVNZ3B3aElqVUdpNVhvNnk4ClBmbGFlU1VOamxiRklvQkFyVWJO
        ZlhSTUVaUUFuN3FkeTJ6ZzVuV0ZFM2sKLS0tIGR5Z2t6Zm5sVkt6OHk5ZnpKeEtp
        OTc0cHRESFZZbzE5WWhiUERkRW4raDgKTacuXflosx1FstVFS5eRfZ4l/vtIuYFK
        4UFSkaszqE1TqkUgxoI9WBJ8n/LpOpmRppyaLZp4M2Vrb/R3bhMkRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T14:03:27Z"
  mac: ENC[AES256_GCM,data:ibGWWU9xHunQVTXPFu7NJy2IJWNSxiRxcIKaUjklNHUJ4ZrqYyueeKXqgSiK4qeyxMz0l5vjty8NBXQ8WvTH1cV//jjNpn5wNJF1jV5XZ98aFK/17oED7/mhmabL0Lce3l7aGif6IRTQz1ER+7BxVqtkjU0sf6xnQXFin2Au3E4=,iv:WrT36lSo1nDUW8NfWrT9wk07jmdw6oqUrjV1JGDaH2Q=,tag:XUacZEwP68WsgsVfVt18xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
