---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
spec:
  configuration:
    destinationPath: s3://tal-postgres/
    endpointURL: http://192.168.1.61:10106
    s3Credentials:
      accessKeyId:
        name: minio
        key: accessKey
      secretAccessKey:
        name: minio
        key: secretKey
    wal:
      compression: zstd
    data:
      compression: gzip
  retentionPolicy: "10d"
