apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:nCcRTFICwz3t85OCJcbVR52eN1sMhkEZGXbuRS4=,iv:hBgJQIwk8gH/EJYodiHH/KlDfLiKmslNV8DttE3L9cE=,tag:a4M5oVkI/XQnXmkmYXkN/A==,type:str]
  accessKey: ENC[AES256_GCM,data:LFA2nTkaksBEu3jg+maKghWINgU=,iv:AhAAqrebKLhixlfAQhq9pNBuOLMAF876yaJB6jnHHYo=,tag:tkR/hJm2TH4cZOV3C8CRVg==,type:str]
  secretKey: ENC[AES256_GCM,data:0WKWtQldERkLaBfwqqaocmRP6wG+w0nqYHO7fD4zHMNSCIeWQeDM3Q==,iv:pBHNqfgsqYcj3lKcJ1yH33sstuG7m3+txeab1g1m4eE=,tag:wFgRv82oauu3Mjw1HI7obg==,type:str]
sops:
  age:
    - recipient: age10yqv86uf4nvjn7q3ftlkellvxkgp839g3vf07kse6gxzpmxz945srd73fx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YjRTaW5JSXU3RHl2YlVE
        WU52SG1qUGZHbWpING9EL25IV1hoOGlXVnpjCk9ydm5PdkdXVW9wUnRBQkFxMGp1
        YWdyUHE2RWM0VU02SHB1aDJmUHIxUE0KLS0tIEdWVGtURDBwdVJzQkNpZ2lQSlFL
        QWFuaXNMVmJubUZ0dmJqQWFLR05GME0K2RHnNUWNbu4Gy27RAJtz7ObtsyzshOMI
        dTKd+0VglrGgAy00TPHiQ5akYcGlObOBTDc7WAMxWd25W+gwt57WHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T15:32:01Z"
  mac: ENC[AES256_GCM,data:FjFjVbQKslwnG5ZV5DJ1GAeiS/WaWF1/D9W/2FRtedHY6fAmq18nXxuzA13KPEHbdWQB8B/qaf/FhriuLbiScUhW9cTnMPaw9+BsbhPyNzs0ORKL/Vf8FIUd5I7dzmlDd7ztpo4lMJfhRz/QEb+Nh8w7gYSBSktV08yHp5LvngE=,iv:hkR3sdOIfGOFCA9SCmTZIG9DIXvrkCr6cigyeqcqF5M=,tag:mE6/dorHRekWqrQIBDwknw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
